### ISSUE TITLE
Pass usage to ArgumentExceptions thrown by command execute invocations

### ISSUE THREAD

**Issue by jontejj** [Softhouse/jargo#43]
Right now:
```
Exception in thread "main" java.lang.NullPointerException: No originParser set for ArgumentException. No usage available.
	at java.util.Objects.requireNonNull(Objects.java:228)
	at se.softhouse.jargo.ArgumentException.getUsage(ArgumentException.java:122)
	at se.softhouse.jargo.ArgumentException.getMessageAndUsage(ArgumentException.java:88)
	at ....
```
is returned instead.

**Comment by jontejj** [comment]
Fixed in the jontejj repo
